"""Atomic persistence for RiverStrategyPolicy (local pickle only)."""

from __future__ import annotations

import json
import logging
import os
import pickle
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import river

from resume_engine.config.settings import ONLINE_LEARNING_STORAGE_DIR, ensure_storage_dirs
from resume_engine.learning.online.config import (
    FEATURE_SCHEMA_VERSION,
    ONLINE_POLICY_VERSION,
)

logger = logging.getLogger(__name__)

POLICY_FILE = "policy.pkl"
POLICY_PREVIOUS = "policy.previous.pkl"
METADATA_FILE = "policy_metadata.json"


def policy_dir() -> Path:
    ensure_storage_dirs()
    path = ONLINE_LEARNING_STORAGE_DIR
    path.mkdir(parents=True, exist_ok=True)
    return path


def _atomic_write_bytes(target: Path, payload: bytes) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=".policy_", suffix=".tmp", dir=str(target.parent))
    try:
        with os.fdopen(fd, "wb") as tmp:
            tmp.write(payload)
            tmp.flush()
            os.fsync(tmp.fileno())
        os.replace(tmp_name, target)
    finally:
        if os.path.exists(tmp_name):
            try:
                os.unlink(tmp_name)
            except OSError:
                pass


def _atomic_write_text(target: Path, text: str) -> None:
    _atomic_write_bytes(target, text.encode("utf-8"))


def save_policy(policy) -> Path:
    """Persist policy with backup of previous pickle."""
    directory = policy_dir()
    target = directory / POLICY_FILE
    previous = directory / POLICY_PREVIOUS
    if target.exists():
        try:
            os.replace(target, previous)
        except OSError:
            # Copy fallback
            previous.write_bytes(target.read_bytes())

    payload = pickle.dumps(policy, protocol=pickle.HIGHEST_PROTOCOL)
    _atomic_write_bytes(target, payload)

    metadata = {
        "policy_version": getattr(policy, "policy_version", ONLINE_POLICY_VERSION),
        "river_version": getattr(river, "__version__", "unknown"),
        "feature_schema_version": FEATURE_SCHEMA_VERSION,
        "created_at": _read_created_at(directory),
        "updated_at": datetime.now(UTC).isoformat(),
        "observation_count": int(getattr(policy, "observation_count", 0)),
        "action_counts": dict(getattr(policy, "action_counts", {}) or {}),
        "reward_mean": getattr(policy, "reward_mean", None),
        "reward_count": int(getattr(policy, "_reward_count", 0)),
    }
    if not metadata["created_at"]:
        metadata["created_at"] = metadata["updated_at"]
    _atomic_write_text(directory / METADATA_FILE, json.dumps(metadata, indent=2))
    return target


def _read_created_at(directory: Path) -> str | None:
    meta_path = directory / METADATA_FILE
    if not meta_path.exists():
        return None
    try:
        data = json.loads(meta_path.read_text(encoding="utf-8"))
        return data.get("created_at")
    except (OSError, json.JSONDecodeError, TypeError):
        return None


def load_policy(*, directory: Path | None = None):
    """
    Load policy pickle generated by this application only.

    Returns None on missing/corrupt files (caller falls back).
    """
    from resume_engine.learning.online.river_policy import RiverStrategyPolicy

    base = directory or policy_dir()
    path = base / POLICY_FILE
    if not path.exists():
        return None
    try:
        with open(path, "rb") as f:
            obj = pickle.load(f)
        if not isinstance(obj, RiverStrategyPolicy):
            logger.warning("ONLINE_POLICY_FALLBACK: unexpected policy type %s", type(obj))
            return None
        return obj
    except Exception as exc:  # noqa: BLE001
        logger.warning("ONLINE_POLICY_FALLBACK: corrupt policy: %s", type(exc).__name__)
        return None


def load_metadata(*, directory: Path | None = None) -> dict[str, Any]:
    base = directory or policy_dir()
    path = base / METADATA_FILE
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
