P1_COVERAGE_MIN = 1.00
P2_COVERAGE_MIN = 0.90
P3_COVERAGE_MIN = 0.60
P4_USAGE_MAX = 0.35

RESPONSIBILITY_COVERAGE_MIN = 0.85
ROLE_ALIGNMENT_MIN = 0.80
BULLET_RELEVANCE_MIN = 0.70
DUPLICATE_SIMILARITY_MAX = 0.84
PASS_SCORE_MIN = 92.0
REPAIR_SCORE_MIN = 88.0

BULLET_WORD_MIN = 10
BULLET_WORD_MAX = 34

# Wave 2
LAYA_BULLET_BATCH_SIZE = 10
LAYA_BATCH_MAX_RETRIES = 2
LAYA_RESPONSIBILITY_MAX = 24  # Gate 2: was hard-coded [:8]
VARIANT_REGEN_MAX = 2
CROSS_RUN_SIMILARITY_MAX = 0.90
VARIANT_SIMILARITY_MAX = 0.92
SCORE_COMPARABLE_EPSILON = 0.5
DEFAULT_VARIANT_COUNT = 5

# Gate 2 — fingerprint signatures
FINGERPRINT_SIMHASH_BITS = 64
FINGERPRINT_MINHASH_PERMUTATIONS = 32
FINGERPRINT_SHINGLE_SIZE = 2
# Hamming distance at/below this (~10% bits) counts as near-duplicate for SimHash.
FINGERPRINT_SIMHASH_MAX_HAMMING = 6
FINGERPRINT_MINHASH_JACCARD_MIN = 0.85

# Wave 3 — self-learning (retrieval/ranking only; not model training)
LEARNING_MIN_SAMPLE_COUNT = 5
LEARNING_HISTORICAL_WEIGHT = 2.0
LEARNING_P1_MIN = 100.0
LEARNING_P2_MIN = 90.0
LEARNING_HYBRID_PROBABILITY_MIN = 0.55

# Wave 4 — LLM client
LLM_TIMEOUT_SECONDS = 90.0
LLM_MAX_RETRIES = 3
LLM_BACKOFF_BASE_SECONDS = 0.5
LLM_BACKOFF_MAX_SECONDS = 8.0
LLM_DUAL_WRITE_SQLITE = True
